### PR TITLE
bolt-rawgen: Write generated code to a new file.

### LINKED ISSUE #2: bolt-rawgen: Please write to a new file
Editing the main source file is just evil. It makes diffs harder to read, it messes with the files open in my editor, and what go generate stuff is out there has already settled into writing new files.

My personal favorite has been to use `*.gen.go` for generated go source. Stringer (https://godoc.org/golang.org/x/tools/cmd/stringer) seems to use `*_string.go`, but that's a bit weird to me because it interacts with build tags..

### PR DESCRIPTION
**Pull request by chrsm**
This should fix #2. I'm not super fond of using a string->string map for imports (considering there's not much to really import), but it seemed cleaner than using a slice and uniq'ing it.

Let me know what you think and/or what adjustments need to be made.

### CODE REVIEW

**Comment by chrsm** [comment]
@tv42 any thoughts here?

**Comment by chrsm** [comment]
Thanks, @tv42! I will work on some of these and get this updated.

**Comment by chrsm** [comment]
@tv42 / @benbjohnson :+1: / :-1: ?

Sorry it took me so long to get back to this PR, had a very busy week at work.

**Comment by chrsm** [comment]
@benbjohnson ping

**Comment by benbjohnson** [comment]
@chrsm Sorry it's taken me so long to respond. I haven't had much time and I'm no longer on the project where I was using `boltdb/raw` so it take me a bit to get back into the headspace in order to review. Do you want take over the repo? I don't think I'm the best person to run it if I'm not actively using it.

**Comment by chrsm** [comment]
@benbjohnson No problemo, just wanted to ping. Re: maintaining the repository, I'm totally fine with that.

**Comment by chrsm** [comment]
@benbjohnson Can I submit a PR to point to my fork, or get access to this one?

**Pull request closed without merging**
